default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: lin097
  host: localhost

development:
  <<: *default
  database: ecomerces2

test:
  <<: *default
  database: ecomerce_tests2